name: Test & Build
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.x

    - name: Get dependencies
      run: |
        go mod vendor

    - name: Go Vet
      run: go vet ./...

    - name: Test
      run: go test ./...

  build:
    # TODO: MATRIX
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Deployment File
        uses: actions/upload-artifact@v3
        with:
          name: stdlib-source.imageref
          path: stdlib-source.imageref
