name: Test & Build
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Get dependencies
      run: |
        go mod vendor

    - name: Go Vet
      run: go vet ./...

    - name: Test
      run: go test ./...

  build:
    # TODO: MATRIX
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs:
      - test
    strategy:
      matrix:
        goarch:
          - amd64
          - arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Compile
        run: go build -o docgen-${{ matrix.goarch }}
        env:
          GOARCH: ${{ matrix.goarch }}

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.goarch }}
          path: docgen-${{ matrix.goarch }}
